name: Auto Build Release (Template)

on:
  schedule:
    - cron: '0 16 * * *'  # 北京时间 0 点触发
  workflow_dispatch:      # 支持手动触发

# 全局配置
env:
  UPSTREAM_OWNER: "moby"      # 上游组织名
  UPSTREAM_REPO: "moby"       # 上游仓库名

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.check.outputs.VERSION }}
      should_build: ${{ steps.check.outputs.SHOULD_BUILD }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # gh 命令需要这个环境变量
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check version and release status
        id: check
        run: |
          # 1. 获取上游最新版本
          # 假设从某个 API 获取到了 docker-v29.0.0
          LATEST_VERSION=$(curl -s "https://api.github.com/repos/${{ env.UPSTREAM_OWNER }}/${{ env.UPSTREAM_REPO }}/releases/latest" | jq -r ".tag_name")
          # TODO: 此处进行 version 格式化
          # docker-v29.0.0 --> 29.0.0
          LATEST_VERSION=${LATEST_VERSION#*v}
          echo "Latest upstream docker version: $LATEST_VERSION"

          # 2. 使用 gh 检查本仓库是否存在该 Release
          # --repo 指定仓库，2>/dev/null 忽略报错日志
          if gh release view "$LATEST_VERSION" --repo ${{ github.repository }} >/dev/null 2>&1; then
            echo "Release $LATEST_VERSION already exists. Skipping."
            echo "SHOULD_BUILD=false" >> $GITHUB_OUTPUT
          else
            echo "Release $LATEST_VERSION not found. Need to build."
            echo "VERSION=$LATEST_VERSION" >> $GITHUB_OUTPUT
            echo "SHOULD_BUILD=true" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check-version
    if: needs.check-version.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Build
        run: |
          chmod +x ./process_version.sh
          ./process_version.sh ${{ needs.check-version.outputs.version }}
      
      - name: Upload
        run: |
          VERSION="${{ needs.check-version.outputs.version }}"
          gh release create "$VERSION" \
            --title "Release $VERSION" \
            --notes "Automated build for $VERSION based on ${{ env.UPSTREAM_OWNER }}/${{ env.UPSTREAM_REPO }}" \
            dists/*
